WITH CTE AS (
    SELECT *
    FROM BOOK
    LEFT JOIN AUTHOR
    USING (AUTHOR_ID)    
), CTE2 AS (
    SELECT *
    FROM CTE
    JOIN BOOK_SALES
    USING (BOOK_ID)
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM CTE2
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY 1 ASC, 3 DESC



