WITH RECURSIVE cte(ID, GEN) AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ed.ID, GEN+1
    FROM cte
    JOIN ECOLI_DATA ed
    ON ed.PARENT_ID = cte.ID
)
SELECT ID
FROM cte
WHERE GEN = 3
ORDER BY ID;