# WITH cte() AS (
#     SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
#     FROM OFFLINE_SALE
#     UNION ALL
#     SELEC T
# JOIN ONLINE_SALE AS onl
# ON off.SALES_DATE = onl.SALES_DATE)
# # SELECT DATE_FORMAT(onl.SALES_DATE, '%Y-%m-%d')

WITH SALE_DATA AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE

    UNION ALL
    
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE
)

SELECT * FROM SALE_DATA
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
    ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

# SELECT * FROM ONLINE_SALE
   