WITH CTE AS (
    SELECT E.EMP_NO, E.EMP_NAME, E.SAL, AVG(G.SCORE) SCORE
    FROM HR_EMPLOYEES E
    JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
    GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL
), CTE2 AS (
    SELECT EMP_NO, (CASE WHEN SCORE >= 96 THEN 'S'
           WHEN SCORE >= 90 THEN 'A'
           WHEN SCORE >= 80 THEN 'B'
           ELSE 'C' END) GRADE
    FROM CTE
), CTE3 AS (
    SELECT EMP_NO, GRADE, (CASE GRADE WHEN 'S' THEN 0.2
                  WHEN 'A' THEN 0.15
                  WHEN 'B' THEN 0.1
                  ELSE 0 END) RATE
    FROM CTE2
)

SELECT C1.EMP_NO, EMP_NAME, GRADE, (RATE * SAL) BONUS
FROM CTE C1
JOIN CTE3 C3
ON C1.EMP_NO = C3.EMP_NO
GROUP BY C1.EMP_NO, EMP_NAME, GRADE, BONUS, RATE
ORDER BY 1