-- 코드를 입력하세요
SELECT info.FLAVOR
FROM ICECREAM_INFO AS info
LEFT JOIN FIRST_HALF AS half
ON info.FLAVOR = half.FLAVOR
WHERE half.TOTAL_ORDER > 3000
AND info.INGREDIENT_TYPE = 'fruit_based'
ORDER BY half.TOTAL_ORDER DESC;
