WITH CTE AS (
    SELECT RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) R, PRICE, PRODUCT_NAME, CATEGORY
    FROM FOOD_PRODUCT 
    GROUP BY PRICE, PRODUCT_NAME)
    
SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME FROM CTE
WHERE R = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC
