WITH sub AS (
    SELECT *
    FROM DEVELOPERS d
    LEFT JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE
)

SELECT 
    CASE
        WHEN ID IN (SELECT ID FROM sub WHERE CATEGORY = 'Front End') AND ID IN (SELECT ID FROM sub WHERE NAME = 'Python') THEN 'A'
        WHEN ID IN (SELECT ID FROM sub WHERE NAME = 'C#') THEN 'B'
        WHEN ID IN (SELECT ID FROM sub WHERE CATEGORY = 'Front End') THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM sub
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
